name: cde-platform
version: '3.8'

services:
  ui: 
    build:
      context: ../../
      dockerfile: ./conf/dev/ui.dockerfile
    container_name: cde-ui
    working_dir: /app
    command: npx vite --host 0.0.0.0 --port 5173
    environment:
      DEBUG: 1
    volumes:
      - ../../web:/app
      - /app/node_modules
    ports:
      - 5173:5173
    restart: on-failure
    networks:
      - cde-network

  api:
    build:
      context: ../../
      dockerfile: ./conf/dev/api.dockerfile
    container_name: cde-api
    working_dir: /app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8001
    environment:
      DEBUG: 1
    volumes:
      - ../../api:/app
    ports:
      - 8001:8001
    restart: on-failure
    depends_on:
      - mongodb
      - elasticsearch
    networks:
      - cde-network
    
  mongodb:
      image: mongo:latest
      container_name: cde-mongodb
      ports:
        - 27017:27017
      volumes:
        - ./mongo-data:/data/db
      networks:
        - cde-network
      
  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: cde-es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es-data:/usr/share/elasticsearch/data
    networks:
      - cde-network

networks:
  cde-network:
    driver: bridge
